---
title:  36-315 Final Project Data Pre-analysis 
author:  Arthur Jakobsson, Alex Cheng, Liz Chu, Kevin Ren 
date:  November 18, 2022 
output:
  html_document:
    toc: yes
    toc_float: yes
    code_folding: show
  pdf_document:
    toc: yes
urlcolor: blue
---

# Rat Sighting Dataset - Data Pre-analysis

```{r} 
# library imports

library(tigris)
library(dplyr)
library(leaflet)
library(tidyverse)
library(sp)
library(ggmap)
library(maptools)
library(broom)
library(httr)
library(rgdal)
library(gridExtra)
library(stringr)
library(geosphere)
# distm(c(lon1, lat1), c(lon2, lat2), fun = distHaversine)
```



```{r, include=FALSE}
rats <- read.csv(file = 'Raw/Rat_Sightings.csv')
# # https://data.cityofnewyork.us/widgets/g642-4e55?mobile_redirect=true
health_inspection <- read.csv(file = 'Raw/DOHMH_New_York_City_Restaurant_Inspection_Results.csv')
# # https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/rs6k-p7g6
drinking_water_inspection <- read.csv(file = 'Raw/Self-Reported_Drinking_Water_Tank_Inspection_Results.csv')
# # https://data.cityofnewyork.us/Health/Self-Reported-Drinking-Water-Tank-Inspection-Resul/gjm4-k24g/data 
subway_entrances <- read.csv(file = 'Raw/SubwayEntrances.csv')
subway_entrances <- subway_entrances %>% add_column(longitude = NA)
subway_entrances <- subway_entrances %>% add_column(latitude = NA)
lats = 1:nrow(subway_entrances)
longs = 1:nrow(subway_entrances)
for (i in (1:nrow(subway_entrances))) {
  longs[i] = as.numeric(sub(".", "", scan(text = subway_entrances$the_geom[i], what = "")[2]))
  lats [i] = as.numeric(str_sub(scan(text = subway_entrances$the_geom[i], what = "")[3],1,-2))
}
subway_entrances$longitude = longs
subway_entrances$latitude = lats

# 
# #NYC map lines
r <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)
# # https://rpubs.com/jhofman/nycmaps
# 
# 
# # clean up rat dataset (remove empty/useless columns)
# rats = subset(rats, select = -c(Agency, Agency.Name,Complaint.Type,  Descriptor ,  Vehicle.Type ,  Taxi.Company.Borough ,  Taxi.Pick.Up.Location , Bridge.Highway.Name ,  Bridge.Highway.Direction ,  Road.Ramp ,  Bridge.Highway.Segment, Facility.Type, Park.Facility.Name) )
# # clean up health inspection dataset (remove empty/useless columns)
health_inspection = subset(health_inspection, select = -c(Location.Point, Zip.Codes, Community.Districts, Borough.Boundaries, City.Council.Districts, Police.Precincts))
```




```{r}
# maps setup

#nice map (manhattan, brooklyn, queens, a bit of bronx)
left =-74.03 
bottom = 40.68 
right = -73.87
top = 40.85
nyc_coords <- c(left, bottom, right, top)

#full map (all boroughs)
leftF = -74.2
bottomF = 40.55
rightF = -73.87
topF = 40.85
nyc_coordsF <- c(leftF, bottomF, rightF, topF)

#just dowtown manhattan
leftM = -74.03
bottomM = 40.69
rightM = -73.94
topM = 40.81
nyc_coordsM <- c(leftM, bottomM, rightM, topM)

nyc_map <- get_stamenmap(nyc_coords, maptype = "terrain", zoom = 11)
nyc_mapF <- get_stamenmap(nyc_coordsF, maptype = "terrain", zoom = 11)
nyc_mapM <- get_stamenmap(nyc_coordsM, maptype = "terrain", zoom = 11)

nyc_neighborhoods_df <- tidy(nyc_neighborhoods) # https://rpubs.com/jhofman/nycmaps

# @here I tried to make this map larger but I couldn't figure out how
nyc_mapPolygon <- ggmap(nyc_map) +
  geom_polygon(data=nyc_neighborhoods_df, aes(x=long, y=lat, group=group), color="blue", fill=NA)

nyc_mapFPolygon <- ggmap(nyc_mapF) +
  geom_polygon(data=nyc_neighborhoods_df, aes(x=long, y=lat, group=group), color="blue", fill=NA)

nyc_mapMPolygon <- ggmap(nyc_mapM) + 
  geom_polygon(data=nyc_neighborhoods_df, aes(x=long, y=lat, group=group), color="blue", fill=NA)

# nyc_mapPolygon
# nyc_mapMPolygon
# nyc_mapFPolygon
```

```{r}
# importing rats

ratSubset <- subset(rats, Longitude<right & Latitude<top & Longitude > left & Latitude >bottom)
ratSubsetF <- subset(rats, Longitude<rightF & Latitude<topF & Longitude > leftF & Latitude >bottomF)
ratSubsetM <- subset(rats, Longitude<rightM & Latitude<topM & Longitude > leftM & Latitude >bottomM)

health_inspection[, c("SCORE")] <- sapply(health_inspection[, c("SCORE")], as.integer)
health_inspection["SCORE"][is.na(health_inspection["SCORE"])] <- 0

healthSubset <- subset(health_inspection, Longitude<right & Latitude<top & Longitude > left & Latitude >bottom & SCORE>50)
healthSubsetF <- subset(health_inspection, Longitude<rightF & Latitude<topF & Longitude > leftF & Latitude >bottomF & SCORE>50)
healthSubsetM <- subset(health_inspection, Longitude<rightM & Latitude<topM & Longitude > leftM & Latitude >bottomM & SCORE>50)

rat_map <- ggmap(nyc_map) +
  geom_point(data=ratSubset, aes(x=Longitude, y = Latitude), alpha=0.2, size =0.01, color = "coral3")

rat_mapF <- ggmap(nyc_mapF) +
  geom_point(data=ratSubsetF, aes(x=Longitude, y = Latitude), alpha=0.2, size =0.01, color = "coral3")

rat_mapM <- ggmap(nyc_mapM) +
  geom_point(data=ratSubsetM, aes(x=Longitude, y = Latitude), alpha=0.2, size =0.01, color = "coral3")

# rat_map
# rat_mapF
# rat_mapM


ratHealthScore_map <- ggmap(nyc_map) +
  geom_point(data=ratSubset, aes(x=Longitude, y = Latitude), alpha=0.2, size =0.01, color = "chocolate3")+
  geom_point(data=healthSubset, aes(x=Longitude, y = Latitude, color = SCORE), size = 0.5, alpha=0.2) +
  scale_color_distiller(palette = "PiYG")

ratHealthScore_mapF <- ggmap(nyc_mapF) +
  geom_point(data=ratSubsetF, aes(x=Longitude, y = Latitude), alpha=0.2, size =0.01, color = "chocolate3")+
  geom_point(data=healthSubsetF, aes(x=Longitude, y = Latitude, color = SCORE), size = 0.5, alpha=0.2) +
  scale_color_distiller(palette = "PiYG")

ratHealthScore_mapM <- ggmap(nyc_mapM) +
  geom_point(data=ratSubsetM, aes(x=Longitude, y = Latitude), alpha=0.2, size =0.1, color = "chocolate3") +
  geom_point(data=healthSubsetM, aes(x=Longitude, y = Latitude, color = SCORE), size = 0.5, alpha=0.2) + 
  scale_color_distiller(palette = "PiYG") + 
  geom_polygon(data=nyc_neighborhoods_df, aes(x=long, y=lat, group=group), color="blue", fill="white", alpha=0.3)

```

```{r}

# ratSubsetM <- subset(rats, Longitude<rightM & Latitude<topM & Longitude > leftM & Latitude >bottomM)

ratSubway_mapF <- ggmap(nyc_mapF) +
  geom_point(data=ratSubsetF, aes(x=Longitude, y = Latitude), alpha=0.05, size =0.1, color = "chocolate3") +
  geom_point(data=subway_entrances, aes(x=longitude, y = latitude), color="red",  size = 1, alpha=0.5) + 
  scale_color_distiller(palette = "PiYG") # + 
  # geom_polygon(data=nyc_neighborhoods_df, aes(x=long, y=lat, group=group), color="blue", fill=NA, alpha=0.3)

# ratHealthScore_map
# ratHealthScore_mapF
# ratHealthScore_mapM
ratSubway_mapF
```



```{r}
# system.time({
# minSubwayDist = function(longitude, latitude)
# {
#   min =  as.integer(.Machine$integer.max)
#   for (i in (1:nrow(subway_entrances)))
#   {
#     distance = distm(c(longitude, latitude), c(longs[i], lats[i]), fun = distHaversine)[1]
#     if(distance<min)
#     {
#       min=distance
#     }
#   }
#   return(min)
# }
# 
# ratSubsetM <- ratSubsetM %>% drop_na(Longitude)
# ratSubsetM <- ratSubsetM %>% drop_na(Latitude)
# # ratsub = rats[1:100,]
# ratSubsetM <- ratSubsetM %>% add_column(minSubwayDistance = NA)
# 
# mindists = 1:nrow(ratSubsetM)
# for(i in (1:nrow(ratSubsetM)))
# {
#   mindists[i] = minSubwayDist(ratSubsetM$Longitude[i], ratSubsetM$Latitude[i])
# }
# ratSubsetM$minSubwayDistance = mindists
# })
```

```{r}
#I want to now do a correlation between "region" and (rat count/area of region). nyc_neighborhoods_df is stored in the same way as states are in HW09.

#should also do proportion of "bad restaurants" to "good restaurants" per region
```

```{r}
# Alex's Rats Visualization
rats = subset(rats, rats$Borough != "Unspecified")
rats_fam = subset(rats, grepl("Family", rats$Location.Type, fixed = TRUE))
rats_fam$simple = ifelse(grepl("1-2", rats_fam$Location.Type, fixed = TRUE), "1-2 Family", "3+ Families")
rats_other = subset(rats, !grepl("Family", rats$Location.Type, fixed = TRUE))
rats_other = rats_other %>% group_by(Location.Type) %>% filter(n() > 300 )
family = ggplot(data = rats_fam, aes(x = Borough)) + 
geom_bar(aes(fill = simple)) + 
labs(
title = "Rat Sightings Count for Family Dwellings",
x = "Borough",
y = "Count",
fill = "Number of Families"
)
non_family = ggplot(data = rats_other, aes(x = Borough)) + 
geom_bar(aes(fill = Location.Type)) + 
labs(
title = "Rat Sightings Count for Non-Family Dwellings",
subtitle = "Must have at least 300 sightings per location type",
x = "Borough",
y = "Count",
fill = "Location Type"
)
grid.arrange(family, non_family, nrow = 2)
```

```{r}

# Liz's Graph 1 EDA
# rats is the unedited version of the dataset !!
# rats = read.csv(file = "Rat_Data.csv")
# rats = subset(rats, select = -c(Agency, Agency.Name, Complaint.Type, Descriptor,
#                                 Vehicle.Type, Taxi.Company.Borough, 
#                                 Taxi.Pick.Up.Location , Bridge.Highway.Name, 
#                                 Bridge.Highway.Direction, Road.Ramp, 
#                                 Bridge.Highway.Segment, Facility.Type, 
#                                 Park.Facility.Name))


library(dplyr)
library(magrittr)
library(knitr)
private = c(
  "1-2 Family Dwelling",
  "1-2 Family Mixed Use Building", 
  "1-2 FamilyDwelling", 
  "1-3 Family Dwelling", 
  "1-3 Family Mixed Use Building", 
  "3+ Family Apartment Building", 
  "3+ Family Apt", 
  "3+ Family Apt.", 
  "3+ Family Apt. Building", 
  "3+ Family Mixed Use Building",
  "3+Family Apt.", 
  "Apartment",
  "Private House",
  "Residence",
  "Residential Building",
  "Residential Property",
  "Single Room Occupancy (SRO)"
)

commercial = c(
  "Cafeteria - Public School",
  "Catering Service", 
  "Commercial Building", 
  "Commercial Property", 
  "Construction Site", 
  "Day Care/Nursery", 
  "Government Building", 
  "Grocery Store",
  "Hospital",
  "Office Building", 
  "Restaurant", 
  "Restaurant/Bar/Deli/Bakery", 
  "Retail Store", 
  "School", 
  "School/Pre-School",
  "Store",
  "Street Fair Vendor", 
  "Summer Camp"
)

public = c(
 "Abandoned Building", 
 "Beach", 
 "Building (Non-Residential)", 
 "Catch Basin/Sewer",
 "Ground",
 "Parking Lot/Garage",
 "Public Garden", 
 "Public Stairs",
 "Street Area", 
 "Vacant Building", 
 "Vacant Lot", 
 "Vacant Lot/Property"
)

other = c(
  "",
  "N/A",
  "Other",
  "Other (Explain Below)"
)

rats$Location.Type[rats$Location.Type %in% private] <- "Private"
rats$Location.Type[rats$Location.Type %in% public] <- "Public"
rats$Location.Type[rats$Location.Type %in% commercial] <- "Commercial"
rats$Location.Type[rats$Location.Type %in% other] <- "Other"
rats$Location.Type <- factor(rats$Location.Type)
rats$Date = as.Date(rats$Created.Date, "%m/%d/%Y")

rats_per_day = rats %>% 
  group_by(Date, Location.Type) %>%
  tally() 

names(rats_per_day) = c("date", "locationtype", "n_rats")

library(tidyverse)
ggplot(data=rats_per_day, aes(x=date, y=n_rats, color=locationtype)) + 
  geom_line(alpha=0.3) + labs(
    title="Number of Rats Recorded on Each Day", 
    subtitle="colored by the type of location",
    x="Date", 
    y="Number of Rats Recorded"
  ) + 
  scale_color_manual("Location Type", 
                     values = c("Other" = "yellow", 
                                "Commercial" = "blue", 
                                "Private" = "red", 
                                "Public" = "green")) 

```

dts <- strptime(time, "%I:%M:%S %p")
dts <- format(dts,format="%I:%M:%S %p")
actual_dates_vector <- c(actual_dates_vector,dts)

```{r}
dts <- strptime(rats$Time[1], "%I:%M:%S %p")
dts
substr(dts[1], 11,13)
```


```{r}
library(stringr)
library(ggplot2)
rats$Time = word(rats$Created.Date, start = 2, end = 3)
rats$Hour = as.numeric(substr(strptime(rats$Time, "%I:%M:%S %p"), 11,13))
ggplot(data=rats, aes(x=Hour)) +
  geom_bar(fill="cornflowerblue") +
  labs(x="Hour of the day", y="Number of rat reportings", title="Number of rat sightings by hour of day")
```

```{r}
head(rats)
```


```

# DO NOT RUN THIS CHUNK! saving this here just to show how the rats with districts are tagged

findDist <- function(lon, lat) {
  finalres = "COULD NOT IDENTIFY"
  for (x in 1:59) {
    tib = shape[x, 1]
    dist = tib$district
    poly = tib$geometry
    pt = st_point(c(lon, lat))
    res = summary(st_within(pt, poly))
    
    
    if (res[1] == "1") {
      finalres <- dist
    } 
  }
  
  return(finalres)
}

for (i in 1:range(nrow(rats2017))[1]) {
  rats$District[i] = findDist(rats$Longitude[i], rats$Latitude[i])
}
rats = subset(rats, District != "COULD NOT IDENTIFY")
write.csv(rats, "rats_district_tagged.csv", row.names=FALSE)


```

```{r}
# Kevin's Bar chart of rats given borough
borough.counts <- as.data.frame(table(rats$Borough))
names(borough.counts) = c("Borough","Count")
borough.counts <- rownames_to_column(borough.counts)
borough.counts <- borough.counts %>%  filter(!row_number() %in% c(1))
borough.counts
ggplot(data = borough.counts, aes(x=Borough, y=Count)) +
  geom_col(aes(fill=Borough))
```



